"""
爬虫工具静态注册表模块。
集中定义并硬编码所有预装的爬虫子工具及数据处理工具的元数据声明（ToolSpec），以备主面板初始化展示。
"""

from __future__ import annotations

from src.studio.base import ToolSpec


TOOLS: list[ToolSpec] = [
    ToolSpec(
        tool_id="youtube_keyword_mining",
        name="YouTube 关键词搜索",
        category="YouTube",
        summary="按关键词和日期范围搜索 YouTube 视频，导出标题、时长、播放量、点赞数、发布时间、视频链接和博主主页链接。",
        entrypoint="src.platforms.youtube.windows.YouTubeKeywordWindow",
        implementation_path="platforms/youtube/keyword.py",
        tags=("YouTube", "search", "keyword", "metrics"),
    ),
    ToolSpec(
        tool_id="youtube_channel_profiles",
        name="YouTube 博主信息",
        category="YouTube",
        summary="从 TXT 读取博主主页链接，导出主页链接、博主名称、频道ID、粉丝量和简介。",
        entrypoint="src.platforms.youtube.windows.YouTubeProfilesWindow",
        implementation_path="platforms/youtube/profiles.py",
        tags=("YouTube", "author", "channel", "profile", "followers"),
    ),
    ToolSpec(
        tool_id="youtube_paired_context_metrics",
        name="YouTube 视频上下文数据",
        category="YouTube",
        summary='读取"视频链接 + 博主主页链接"TXT，定位目标视频，并导出目标前后各 5 条视频指标。',
        entrypoint="src.platforms.youtube.windows.YouTubeContextWindow",
        implementation_path="platforms/youtube/context.py",
        tags=("YouTube", "context", "metrics", "txt"),
    ),
    ToolSpec(
        tool_id="youtube_channel_works",
        name="YouTube 博主作品采集",
        category="YouTube",
        summary="按博主主页链接采集视频类作品和 Posts；Videos/Shorts 使用 YouTube API，Posts 使用页面采集。",
        entrypoint="src.platforms.youtube.windows.YouTubeChannelWorksWindow",
        implementation_path="platforms/youtube/channel_works.py",
        tags=("YouTube", "channel", "videos", "shorts", "posts"),
    ),
    ToolSpec(
        tool_id="youtube_top_comments",
        name="YouTube 热门评论",
        category="YouTube",
        summary="读取每行一个视频链接的 TXT，导出每个视频点赞量最高的前 100 条主楼评论。",
        entrypoint="src.platforms.youtube.windows.YouTubeCommentsWindow",
        implementation_path="platforms/youtube/comments.py",
        tags=("YouTube", "comments", "top", "txt"),
    ),
    ToolSpec(
        tool_id="x_keyword_video_search",
        name="X 关键词搜索",
        category="X/Twitter",
        summary="按关键词和日期范围搜索 X 推文，导出含视频或图片的原创媒体推文。",
        entrypoint="src.platforms.x_twitter.windows.XKeywordWindow",
        implementation_path="platforms/x_twitter/keyword.py",
        tags=("X", "Twitter", "search", "media", "slice"),
    ),
    ToolSpec(
        tool_id="x_keyword_author_works",
        name="X 关键词作者作品采集",
        category="X/Twitter",
        summary="按关键词发现 X 作者，再通过 X 搜索页进入作者主页采集简介、粉丝数和最新作品标题；快速模式默认每作者最多取最新 50 条。",
        entrypoint="src.platforms.x_twitter.windows.XKeywordAuthorWorksWindow",
        implementation_path="platforms/x_twitter/keyword_author_works.py",
        tags=("X", "Twitter", "keyword", "author", "profile", "works"),
    ),
    ToolSpec(
        tool_id="x_tweet_author_profiles",
        name="X 博主信息",
        category="X/Twitter",
        summary="从 TXT 读取推文链接或博主链接，提取主页、名称、账号ID、粉丝数和简介；博主链接模式会先通过 X 搜索页进入主页。",
        entrypoint="src.platforms.x_twitter.windows.XProfilesWindow",
        implementation_path="platforms/x_twitter/profiles.py",
        tags=("X", "Twitter", "tweet", "profile", "followers"),
    ),
    ToolSpec(
        tool_id="x_paired_context_metrics",
        name="X 推文上下文数据",
        category="X/Twitter",
        summary='读取"推文链接 + 博主主页链接"TXT，导出目标推文前后各 5 条推文指标。',
        entrypoint="src.platforms.x_twitter.windows.XContextWindow",
        implementation_path="platforms/x_twitter/context.py",
        tags=("X", "Twitter", "context", "metrics", "txt"),
    ),
    ToolSpec(
        tool_id="x_tweet_metrics",
        name="X 推文详情采集",
        category="X/Twitter",
        summary="读取每行一个推文链接的 TXT，导出推文内容、浏览量、评论数、点赞数和转发量。",
        entrypoint="src.platforms.x_twitter.windows.XTweetMetricsWindow",
        implementation_path="platforms/x_twitter/tweet_metrics.py",
        tags=("X", "Twitter", "tweet", "metrics", "txt"),
    ),
    ToolSpec(
        tool_id="x_profile_tweets",
        name="X 博主推文采集",
        category="X/Twitter",
        summary="按博主主页链接先通过 X 搜索页进入作者主页，再采集最新推文样本；默认每个博主最多取最新 50 条，只采作者作品本身，不采评论。",
        entrypoint="src.platforms.x_twitter.windows.XProfileTweetsWindow",
        implementation_path="platforms/x_twitter/profile_tweets.py",
        tags=("X", "Twitter", "profile", "tweets", "timeline"),
    ),
    ToolSpec(
        tool_id="x_profile_bundle",
        name="X 博主信息+推文采集",
        category="X/Twitter",
        summary="按博主主页链接先通过 X 搜索页进入作者主页，再采集作者简介、粉丝数和最新推文样本；默认每个作者最多取最新 50 条。",
        entrypoint="src.platforms.x_twitter.windows.XProfileBundleWindow",
        implementation_path="platforms/x_twitter/profile_bundle.py",
        tags=("X", "Twitter", "profile", "tweets", "bundle", "distributed"),
    ),
    ToolSpec(
        tool_id="tiktok_keyword_metrics",
        name="TikTok 关键词搜索",
        category="TikTok",
        summary="按关键词搜索 TikTok，并按日期范围过滤发布时间，导出视频标题、播放量、点赞数、收藏量、评论数等指标。",
        entrypoint="src.platforms.tiktok.windows.TikTokKeywordWindow",
        implementation_path="platforms/tiktok/keyword.py",
        tags=("TikTok", "search", "video", "metrics"),
    ),
    ToolSpec(
        tool_id="tiktok_keyword_author_works",
        name="TikTok 关键词作者作品采集",
        category="TikTok",
        summary="按关键词发现 TikTok 博主，进入博主主页采集简介、粉丝数和最新视频；输出“博主信息”“博主对应视频”两个分表，快速模式默认每作者最多取最新 50 条。",
        entrypoint="src.platforms.tiktok.windows.TikTokKeywordAuthorWorksWindow",
        implementation_path="platforms/tiktok/keyword_author_works.py",
        tags=("TikTok", "keyword", "author", "profile", "works"),
    ),
    ToolSpec(
        tool_id="tiktok_hashtag_author_works",
        name="TikTok 话题作者作品采集",
        category="TikTok",
        summary="按话题关键词自动生成 TikTok tag 页面发现博主，进入博主主页采集简介、粉丝数和最新视频；输出“博主信息”“博主对应视频”两个分表，无效话题会自动跳过。",
        entrypoint="src.platforms.tiktok.windows.TikTokHashtagAuthorWorksWindow",
        implementation_path="platforms/tiktok/hashtag_author_works.py",
        tags=("TikTok", "hashtag", "tag", "author", "profile", "works"),
    ),
    ToolSpec(
        tool_id="tiktok_profile_directory",
        name="TikTok 博主信息",
        category="TikTok",
        summary="按博主主页链接批量提取博主主页链接、博主名称、博主ID、粉丝量和简介。",
        entrypoint="src.platforms.tiktok.windows.TikTokProfilesWindow",
        implementation_path="platforms/tiktok/profiles.py",
        tags=("TikTok", "profile", "followers", "bio"),
    ),
    ToolSpec(
        tool_id="tiktok_profile_videos",
        name="TikTok 博主视频采集",
        category="TikTok",
        summary="读取博主主页 TXT，按日期范围收集主页视频链接，并进入详情页导出简介、点赞数、评论数和收藏量。",
        entrypoint="src.platforms.tiktok.windows.TikTokProfileVideosWindow",
        implementation_path="platforms/tiktok/profile_videos.py",
        tags=("TikTok", "profile", "videos", "metrics", "date"),
    ),
    ToolSpec(
        tool_id="tiktok_profile_play_counts",
        name="TikTok 博主视频播放量",
        category="TikTok",
        summary="拦截 API 采集博主主页所有视频的链接和播放量，不受创作者隐藏设置影响。",
        entrypoint="src.platforms.tiktok.windows.TikTokProfilePlayCountsWindow",
        implementation_path="platforms/tiktok/profile_play_counts.py",
        tags=("TikTok", "profile", "play_count", "api"),
    ),
    ToolSpec(
        tool_id="tiktok_paired_context_metrics",
        name="TikTok 视频上下文数据",
        category="TikTok",
        summary='读取"视频链接 + 博主主页链接"TXT，在博主主页定位目标视频并导出前后视频指标。',
        entrypoint="src.platforms.tiktok.windows.TikTokContextWindow",
        implementation_path="platforms/tiktok/context.py",
        tags=("TikTok", "context", "metrics", "txt"),
    ),
    ToolSpec(
        tool_id="tiktok_top_comments",
        name="TikTok 热门评论",
        category="TikTok",
        summary="读取每行一个视频链接的 TXT，通过视频页评论接口抓取主楼评论并导出点赞量最高的前 100 条。",
        entrypoint="src.platforms.tiktok.windows.TikTokCommentsWindow",
        implementation_path="platforms/tiktok/comments.py",
        tags=("TikTok", "comments", "top", "txt"),
    ),
    ToolSpec(
        tool_id="instagram_profile_works",
        name="Instagram 博主作品采集",
        category="Instagram",
        summary="按博主主页链接滚动采集公开作品，导出作品ID、链接、发布时间、内容和可识别指标。",
        entrypoint="src.platforms.instagram.windows.InstagramProfileWorksWindow",
        implementation_path="platforms/instagram/works.py",
        tags=("Instagram", "profile", "works", "posts", "reels"),
    ),
    ToolSpec(
        tool_id="judge_aigc",
        name="AIGC 内容判断",
        category="数据处理",
        summary="读取 TXT 文件中的序号和标题，判断是否为 AIGC 内容，并识别主要语言，导出 XLSX 结果。",
        entrypoint="src.processing.windows.JudgeAIGCWindow",
        implementation_path="processing/judge_aigc.py",
        tags=("AIGC", "judge", "title", "xlsx"),
    ),
    ToolSpec(
        tool_id="xlsx_merge",
        name="XLSX 文件合并",
        category="数据处理",
        summary="选择文件夹，默认只合并文件名包含 keyword 的 .xlsx 文件，并重新生成连续序号。",
        entrypoint="src.processing.windows.XlsxMergeWindow",
        implementation_path="processing/xlsx_merge.py",
        tags=("xlsx", "merge", "keyword", "data"),
    ),
]

__all__ = ["TOOLS"]
